# Generated by Django 4.1 on 2023-04-22 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_tags_alter_author_about_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_author',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
